metadata:
  generateName: tipocket-cdc-
  namespace: argo
spec:
  entrypoint: call-tipocket-cdc
  onExit: call-export-logs
  templates:
    - name: call-export-logs
      steps:
        - - name: call-export-logs
            templateRef:
              name: export-logs
              template: export-logs
            arguments:
              parameters:
                - name: ns
                  value: tipocket-cdc
    - name: call-tipocket-cdc
      steps:
        - - name: call-tipocket-cdc
            templateRef:
              name: tipocket-cdc
              template: tipocket-cdc
            arguments:
              parameters:
                - name: ns
                  value: tipocket-cdc
                - name: purge
                  value: "false"
                - name: image_version
                  value: release-4.0-nightly
                - name: storage_class
                  value: pd-ssd
                - name: nemesis
                  value: ""
                - name: run_time
                  value: "60m"
                - name: relay_log
                  value: "true"